"""added issue model and form

Revision ID: 71645d4133bc
Revises: a33a55152e38
Create Date: 2022-03-25 11:56:50.410939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71645d4133bc'
down_revision = 'a33a55152e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('complaint', sa.String(length=1023), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issues')
    # ### end Alembic commands ###
